name: Build, Check Artifact, and Upload (Node.js)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d build ]; then
            echo "No build directory found!"
            exit 1
          else
            echo "Build folder found:"
            ls -lh build
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-build
          path: build/
