name: Build, Check Artifact, and Upload (Node.js)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: echo "No build step needed for Node.js API"

      - name: Verify build output
        run: echo "Skipping build directory check"


      - name: Verify project files
        run: |
         echo "Project files found:"
         ls -lh
      - name: Upload source
        uses: actions/upload-artifact@v4
        with:
         name: node-source
         path: .

